### ISSUE TITLE
Virtual inheritance and dynamic_cast do not work on mocks

### ISSUE THREAD

**Issue by dascandy** [dascandy/hippomocks#10]
This uses other information from the vtable that is not currently available. TODO: figure out if it is possible to make this work.

**Comment by dascandy** [comment]
Added on cpp11 branch, with a test that dynamic_casts in a diamond inheritance. Works fine on GCC. MSVC support pending.

**Comment by rianquinn** [comment]
FYI... this is still an issue with GCC 5.x. Just ran into this exact case, and once you perform the dynamci_cast, the program seg_faults.

**Comment by dascandy** [comment]
Did you use the cpp11 branch, and if so, do you have a reproduction case for it?

**Comment by rianquinn** [comment]
@dascandy sorry... didn't notice the new branch. Works like a charm... thanks a ton for fixing that issue. 

On a side note, do you have any plans to merge the includes into a single header in the future?
