### ISSUE TITLE
visual studio tests failed in release configuration

### ISSUE THREAD

**Issue by soyersoyer** [dascandy/hippomocks#13]
With VS2012:
hippomocks\HippoMocksTest\Release>HippoMocksTest_2012.exe
Test checkFunctionReplacedAndChecked failed with exception: a()(1) != 2(2)
Test checkFunctionReturnedToOriginal failed with exception: a()(1) != 2(2)
73 of 75 tests successful

With VS2010:
\hippomocks\HippoMocksTest\Release>HippoMocksTest.exe
Test checkFunctionReplacedAndChecked failed with exception: a()(1) != 2(2)
Test checkFunctionReturnedToOriginal failed with exception: a()(1) != 2(2)
73 of 75 tests successful

in debug configurations are all successful

**Comment by rzr** [comment]
This is also happening on my debian systems  when optimization flags are activated (-O1 or -O2)

g++ --version
g++ (Debian 4.9.2-10) 4.9.2
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4

I fear the problem has always been there (at least it is in cccba75eb4668a6a0ca177e731e26968e26c0c69 where cmake support was introduced)

**Comment by dascandy** [comment]
This is why fundamentally you cannot run tests that use C function mocking in any form of release / optimization mode. When you enable optimization it will inline functions, so it will not have a unique address. That then implies that it cannot mock such a function any more. There's nothing to do about this other than disabling debugging, honestly.

Note that the main use of C function mocking is to mock out OS dependencies.

**Comment by rzr** [comment]
Maybe it could be safe to test if code is inlined and exit with a meaningful message.

ps: I'll might get access to a MIPS board through ssh , so I could help you.

**Comment by dascandy** [comment]
If there is a way to test for that it would be great to add, but as far as I can tell there's no way to do that. C++ only gives you the guarantee that when you have a function pointer to a function, that invoking it will somehow end up invoking that function. You're not guaranteed to have the unique handle to that function, neither locally nor remotely. In fact, if you link dynamically against, say, libc on Linux, you have three entry points that could be called "malloc" - the actual function, the malloc PLT entry in libc itself (for when you override it), and the PLT entry in your application (to point to libc lazily). The one that will be mocked is the PLT entry in your own app, so any libc function calling malloc will still end up calling the actual one.

In the end not really a fixable problem from this point of view; it would require a paradigm shift and a major tool rewrite to ensure that functions have only one actual address. And even then you can still have inlined functions - especially with more LTO/LTCG usage - where you're still not holding the address of the actual code that will be called.
