### ISSUE TITLE
Tracking a compile warnings when mocking some win32 APIs with MSVC

### ISSUE THREAD

**Issue by TTimo** [dascandy/hippomocks#19]
Hello..

MSVC 2010 - latest hippomock

Mocking some win32 API calls. It works, but I'm getting one of those long winded template warnings:

c:\br\src\unittesting\cppunit\hippomocks.h(464): warning C4800: 'volatile long *' : forcing value to bool 'true' or 'false' (performance warning)
[..]
1>          c:\br\src\unittesting\xpaunittests\ipc_client_ut_win32.cpp(68) : see reference to class template instantiation 'HippoMocks::TCall<Y,A,B,C,D,E,F,G,H,I,J,K,L,M,N,O,P>' being compiled
1>          with
1>          [
1>              Y=LONG,
1>              A=volatile LONG *,

The test is basically:

	MockRepository mocks;
	mocks.OnCallFunc(InterlockedIncrement);

Just curious if there's a way to avoid that warning

**Comment by dascandy** [comment]
I'm not quite sure how it would generate that warning. The code around that line is printing code, which should not be coercing your argument at all. 

Do you have the full compile warning still? It would help to determine what's going on. Apologies for taking so long to react.

**Comment by TTimo** [comment]
no sorry, I don't work with hippomock + MSVC 2010 anymore
