### ISSUE TITLE
Hippomock can crash your tests with ODR violation on Windows

### ISSUE THREAD

**Issue by rossmacgregor** [dascandy/hippomocks#25]
In the hippomocks header the following pragma is defined:
```
// Tell Microsoft to conform to C++ (as far as is possible...)
#pragma pointers_to_members(full_generality, virtual_inheritance)
```
If you are not very careful  and compile all your code with this setting it can lead to mysterious crashes in your unit tests because you have violated the C++ one definition rule. 

I assume that most users are blissfully unaware of this fact, therefore, I strongly recommend this setting be removed and avoid your users long debugging sessions tracking down this problem. It took me a long time to find this problem and I can imagine others not even getting that far.

The awesome thing about fixing this bug is it is not even needed! The pragma is apparently a remnant of an old version and still works without it. Please correct me if I am wrong about that.

In my version of hippomocks from 2010-12-14 (sorry, I'm a little behind) I removed the pragma and it's been working fine (for like 2 years now). I did need to make a small change to get the code to complie without the pragma. I needed to add the " = {}" to the code below:

```
#elif defined(_MSC_VER)
	union {
		T t;
		struct
		{
			unsigned char *value;
			unsigned long baseoffs;
		} u;
	} conv = {};
```
Why this is, is a bit of a mystery to me.

**Comment by dascandy** [comment]
> http://www.codeproject.com/Articles/7150/Member-Function-Pointers-and-the-Fastest-Possible

There you will find the explanation:

> Microsoft compilers use an optimization that ... discards the entries which will always be zero. This means that single-inheritance pointers are the size of simple function pointers, multiple inheritance pointers are larger, and virtual inheritance pointers are larger still. This saves space. But it's not standard-compliant, and it has some bizarre side-effects.

> Firstly, casting a member function pointer between a derived class and a base class can change its size! Consequently, information can be lost. Secondly, when a member function is declared before its class is defined, the compiler has to work out how much space to allocate to it. But it can't do this reliably, because it doesn't know the inheritance nature of the class until it's defined. *It has to guess. If it guesses wrongly in one source file, but correctly in another, your program will inexplicably crash at runtime.*

**Comment by dascandy** [comment]
Given the feedback on this subject I've removed the pragma to let MSVC do what it does. I will refer to this entry when/if I get crash reports on this.
