### ISSUE TITLE
dynamic_cast fails on repo.Mock interfaces after casting to a parent type.

### ISSUE THREAD

**Issue by mattboelter** [dascandy/hippomocks#33]
If you create a mock object from the repo and cast it to a parent class, you cannot dynamic_cast it back to interface.  The mock object is not an implementation of the interface, so it fails the dynamic cast back to the interface type.  This code will reproduce the issue in VS2012 32bit & 64bit.  Other compilers should also fail.

    #include "hippomocks.h"

    class IBase
    {
        virtual ~IBase();
    };

    class IInterface : public IBase
    {
    public:
        virtual ~IInterface();

        virtual void DoWork() = 0;
    };

    void main()
    {
        MockRepository  mockRepo;
        auto pIf = mockRepo.InterfaceMock<IInterface>();

        auto pIBase = dynamic_cast<IBase*>(pIf);
        auto pIf2 = dynamic_cast<IInterface*>(pIBase);  // this will fail due to a lack of RTTI info for IInterface
    }

**Comment by dascandy** [comment]
Same issue as #10 ... this is known but takes quite a bit of work to add. I'll look into it again, but specifically for MSVC it's very hard as it is not as open source as Clang/LLVM or GCC are.

**Comment by dascandy** [comment]
@mattboelter I've just committed a fix for GCC/Clang that makes this (and other dynamic_casts, and typeid) work properly. I'll look at MSVC sometime soon.
