### ISSUE TITLE
Unable to return a const ref of an abstract class

### ISSUE THREAD

**Issue by dkgs** [dascandy/hippomocks#36]
There is a compile error with the following test case : 
```c++
#include "HippoMocks/hippomocks.h"
    
class B {
public:
   virtual ~B() = 0 {}
    
   virtual void doSomething() const = 0;
    
};
    
class A {
public:
   virtual ~A() = 0 {}
    
   virtual const B & getB() const = 0;
       
};

int main(int argc, char * argv[])
{
   MockRepository mocks;

   B * b = mocks.Mock<B>();
   A * a = mocks.Mock<A>();

   mocks.OnCall(a, A::getB).Return(*b);
   mocks.ExpectCall(b, B::doSomething);

   a->getB().doSomething();

   mocks.VerifyAll();
}
```

It is caused because the ReturnValueHolder does not accept const ref and force the value to be copyable. There is no problem if my methods and return values are non-const.
It seems it is directly related to the comit 72544aa2c7a0b7cb71ab6c6c2421b8b08417fc95 to permit the Return of ref temporay values.

I'm going to see if I can setup a workaround.

**Comment by dascandy** [comment]
Is this the issue you had the submit for? If so, can I close it?

**Comment by dkgs** [comment]
Yes it is, you can close this issue.
