### ISSUE TITLE
Adding COM Support (stdcall) for msvc compiler

### ISSUE THREAD

**Issue by mrAtari** [dascandy/hippomocks#41]
I investigated the problem and found a solution (including some new tests).
I would like to contribute to the project. 
Would please someone give me a hint how?

**Comment by dascandy** [comment]
... That's interesting, as stdcall support should have been there already, for a few years now.

For contributing, you first create a fork of the project (top-right corner), then modify it and commit to your  own fork (using your github account details). Then, when you're done you send a pull request (should be able to google how/where to do this, but I'm fairly sure it's advertised on the page).

Do  you have a description what doesn't work for you?

**Comment by mrAtari** [comment]
Code was not even compileable for stdcall Interfaces (e.g. getFunctionIndex not declared amongst other things)
I'm preparing a branch with the fixes.

**Comment by mrAtari** [comment]
Committed the fixes and created my very first pull request on GitHub.

Comments and suggestions for improvvement are welcome.

**Comment by dascandy** [comment]
I think this is now fixed - I recall merging your requests. I've updated most of the code to c++11, can you check the cpp11 branch if it works for you?
