### ISSUE TITLE
Version number?

### ISSUE THREAD

**Issue by grahamreeds** [dascandy/hippomocks#56]
The assembla page from 2009 is version 3.1.  What version are we on now?  Need one for a manifest:-(

**Comment by dascandy** [comment]
... Good point. I hadn't realized it was that long ago already. Will try to release a tag tonight; it'll be v5.0 with the current github sources.

**Comment by grahamreeds** [comment]
No worries.  Can't use anyway as you specify CMake 3 as a minimum and we are tied to 14.04 LTS (2.8.12.2).  Had a quick check to see if changing the version would work.

> CMake Error at HippoMocks/CMakeLists.txt:3 (add_library):
>   Cannot find source file:
> 
>     INTERFACE
> 
>   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
>   .hxx .in .txx
>

**Comment by dascandy** [comment]
Aah... you can add a dummy CPP file and make it STATIC to get the same result. CMake used to be a bit stupid about this (and kind of still is, but in a different way now).

**Comment by torbjoernk** [comment]
Would it be possible to create Git tags for specific versions? That would enable GitHub's release feature as well.

**Comment by dascandy** [comment]
@torbjoernk @grahamreeds Looks like this succeeded finally. There's now a v5.0 release and it's tagged as the current version. I'll try to add tags for the previous versions too.
