### ISSUE TITLE
Package HippoMocks for apt

### ISSUE THREAD

**Issue by dascandy** [dascandy/hippomocks#63]

**Comment by rzr** [comment]
apt like debian ?

I started to do that, maybe I can resume doing this

https://bugs.debian.org/826582

It would also help to have a version tagged  (ie 0.0.20161201)

There you'll get feedback from MIPS users 
https://github.com/dascandy/hippomocks/pull/50

**Comment by dascandy** [comment]
.. Yes, actually. I was thinking Ubuntu, but I believe Ubuntu is still downstream from Debian - or at least uses the same kind of packages. If you could do this that would be great.

**Comment by rzr** [comment]
yes If it goes into debian it will land into ubuntu , mint etc

About tagging is it possible  to have one tag for year 2016 at least :)

**Comment by dascandy** [comment]
There already is a tag called "v5.0" which is the last c++03 version. Hope that's OK?

**Comment by rzr** [comment]
ok good I will forward patches if needed

**Comment by rzr** [comment]
Master and v5.0 seems good,

Do you plan to tag a new version soon, if so please also check my comments:
https://github.com/dascandy/hippomocks/issues/52

**Comment by rzr** [comment]
Track:

https://qa.debian.org/developer.php?login=rzr@users.sf.net

https://tracker.debian.org/pkg/hippomocks

Then close:
https://github.com/dascandy/hippomocks/issues/63

may I suggest to double licence to make sure the LGPLv2 inlined code from header will fit along other clients.

**Comment by rzr** [comment]
Track build errors at:
https://buildd.debian.org/status/package.php?p=hippomocks

mips:
https://buildd.debian.org/status/fetch.php?pkg=hippomocks&arch=mips&ver=5.0-1&stamp=1516912910&raw=0

arm64:
https://buildd.debian.org/status/fetch.php?pkg=hippomocks&arch=arm64&ver=5.0-1&stamp=1516909431&raw=0
https://github.com/dascandy/hippomocks/issues/73

**Comment by dascandy** [comment]
Thanks! Looks excellent - I got a Google notification that it's findable too.

**Comment by rzr** [comment]
your're welcome,

Please also check

https://github.com/dascandy/hippomocks/issues/52

-- 
gpg:0x467094BC
mailto:rzr@users.sf.net
http://rzr.online.fr/

**Comment by rzr** [comment]
For ubuntu track:

https://launchpad.net/ubuntu/+source/hippomocks

**Comment by rzr** [comment]
Also in raspbian:

http://archive.raspbian.org/raspbian/pool/main/h/hippomocks/
http://archive.raspbian.org/raspbian/pool/main/h/hippomocks/hippomocks_5.0-1_armhf.deb
