### ISSUE TITLE
cpp11 branch cannot compile with Visual Studio 2013

### ISSUE THREAD

**Issue by mrAtari** [dascandy/hippomocks#66]
Seems to have a lot of different issues inside.
Just 2, I found after a short inspection:

First one: noexcept supported only since VS2015
` ~MockRepository()
  // If we're on a recent enough compiler that's not VS2012 (as it doesn't have noexcept)
#if __cplusplus > 199711L || (defined(_MSC_VER) && _MSC_VER > 1800)
noexcept(false)
#endif`

Second: I'm not sure, but RegisterExpect seems to resolve to the stdcall overload by default.
May be there's an overload mission for the standard case

Lot's of the testcases don't compile at all.

**Comment by dascandy** [comment]
I tried on MSVC2015, and if I leave out the ComSupport stuff I get no errors, but a ton of warnings. That's because I removed the whole-file warning disables.

With 3 targeted warning disables all of those are quiet now. Two are about a template parameter being compared to a constant - yes, that's a compile-time fixed thing and it should not warn about it, but use the info. The third is a warning on the invoke function:

    template <typename Y, typename... Args, int... Nums>
    Y _invoke(const std::function<Y(Args...)> &func, seq<Nums...>, const std::tuple<Args...>& args) {
      return func(std::get<Nums>(args)...);
    }

which it claims does not use the "args" argument. I cannot see why it would think that, but it's used.

**Comment by dascandy** [comment]
It looks like the 2013 compiler just doesn't get the invoke function. It has no idea how to derive arguments, and it refuses to understand it. Could be a known C++11 problem with '13 - it wouldn't be the first bug I find in that.

**Comment by mrAtari** [comment]
Here's a table, which features are supported by which VS compiler: [https://msdn.microsoft.com/library/hh567368.aspx#corelanguagetable](url)

IMHO it makes little sense to use all the great new features of the standard, because the number of users. which can profit from that is too small. (For example in our company there's no single project with VS2015, many are still using VS2008. On the embedded side it's not better, projects are still using gcc2)

Maybe it's a better idea to focus on the most valuable enhancements, like variadic templates and make it run on the biggest number of compilers.

**Comment by dascandy** [comment]
The point of the C++11 branch is to be able to use HippoMocks if you need some C++11 features that are not supported in C++03, while at the same time cleaning up the code inside HippoMocks using features that are widely available. VS2008 and VS2010 support so little of C++11 that they just don't apply at all, while VS2012 has too many omissions to be possible. VS2013 would be OK, if it works - but I've already found multiple bits of valid code that it just won't take.

**Comment by mrAtari** [comment]
The error is probably caused, by the sizeof operator:
`template <typename Y, typename... Args>

Y invoke(const std::function<Y(Args...)> &func, const std::tuple<Args...>& args) 

{
    return _invoke<Y, Args...>(func, typename gen<**sizeof**...(Args)>::type(), args);
}`

**Comment by mrAtari** [comment]
If you check it in, I can run the tests with VS2013.

**Comment by dascandy** [comment]
Last commit should fix all issues with '13 and '15. Note, default compiler in MSVC project is still '12, so check that it's set correctly before you try.

Problems fixed:
- MSVC2013 confused by invoke. Replaced invoke by different form.
- MSVC2013 supports aggregate initializers but doesn't realize it. Suppressed all warnings related to "uninstantiatable class" that was used correctly, and that works.
- QueryInterface is an overload set, not just a function. Disambiguated OnCalls to it.
- MSVC2015 now has warnings on local vars that conflict with members. That's good - but we had that. Fixed.

**Comment by dascandy** [comment]
@mrAtari Does it work for you too? I've checked with MSVC2013, 2015 and 2017 here and all three are fine with it. 2013 keeps some warnings, but 2015 and 2017 correctly use the warning disable around template and are warning free on /W4.

**Comment by mrAtari** [comment]
VS2013 Compiles && tests are ok. Including COM tests.

Add the following 2 changes, and it will compile without any warnings:
1. In Framework.h replace vsnprintf with vsnprintf_s
2. Move the pragma warning disable at file level (where the other Visual studio pragmas are)

**Comment by dascandy** [comment]
The pragma warning disables should be as narrow as possible. I'd like it if they weren't needed at all, actually. Testing on MSVC2017 reveals they all do nothing now, except for the 4121 for alignment in a union (????).

**Comment by dascandy** [comment]
Removed all old warning disables and set the narrowest that I could. It's now warning free on MSVC2013 (and implicitly on 2015 and 2017 too).
