### ISSUE TITLE
Out of memory on test

### ISSUE THREAD

**Issue by rzr** [dascandy/hippomocks#85]
Hi while building on debian I figured out an issue on running test,

So I bypassed this for the packaging effort at:
https://github.com/dascandy/hippomocks/issues/63

I can share more details if anyone care

**Comment by dascandy** [comment]
Please do. Last time somebody found an OOM was on Windows with a weird exception handling thing.

**Comment by rzr** [comment]
Sorry this can be closed , I did not strip out optimization flags
