### ISSUE TITLE
[cpp11 branch] std::uncaught_exception is deprecated in C++17

### ISSUE THREAD

**Issue by torbjoernk** [dascandy/hippomocks#95]
`std::uncaught_exception` is deprecated in C++17 and replaced by `std::uncaught_exceptions` (the plural form).

At least MSVC 14.14 is issuing warnings (C4996):
```
hippomocks\hippomocks.h(908): warning C4996: 'std::uncaught_exception': warning STL4006: std::uncaught_exception() is deprecated in C++17. It is superseded by std::uncaught_exceptions(), plural. You can define _SILENCE_CXX17_UNCAUGHT_EXCEPTION_DEPRECATION_WARNING or _SILENCE_ALL_CXX17_DEPRECATION_WARNINGS to acknowledge that you have received this warning.
```

**Comment by dascandy** [comment]
Will get back to this and other issues when I get back from holidays.

**Comment by eduardoaugustojulio** [comment]
Hey guys any news about this one?

**Comment by hexagonrecursion** [comment]
* [uncaught_exception() was removed in C++20](https://en.cppreference.com/w/cpp/error/uncaught_exception)
* It looks like there is a pull request to fix the issue: https://github.com/dascandy/hippomocks/pull/115

**Comment by PeterBindels-TomTom** [comment]
Thanks for poking; I merged it.

**Comment by dascandy** [comment]
Thanks for poking; I merged it.
